/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3Paradigma;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public int semiSuma(int x, int y)
    {
        return ((x+y)/2);
    }

    public static void main(String[] args) {
        System.out.println(new App().semiSuma(2,10));
    }
}
